
TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /home/lqi/lqi_temp/trainingspace/pretrained_models/I3D_NLN_8x8_R50.pkl
  CHECKPOINT_TYPE: caffe2
  MIXED_PRECISION: True

TEST:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 4
  CHECKPOINT_FILE_PATH: /home/lqi/lqi_temp/trainingspace/results/I3D_NLN_8x8_R50/checkpoints/checkpoint_epoch_00040.pyth

OUTPUT_DIR: /home/lqi/lqi_temp/trainingspace/results/evaluations/I3D_NLN_8x8_R50

AVA:
  # train and test file need to be changed for different work

# -------------- For TRAIN.ENABLE: TRUE and TEST.ENABLE: FALSE ------------------

  # GROUNDTRUTH_FILE: "ava_val_gt.csv"
  # TEST_LISTS: ["val.csv"]
  # TEST_PREDICT_BOX_LISTS: ["ava_val_predicted_boxes.csv"]

# -------------- For TRAIN.ENABLE: FALSE and TEST.ENABLE: TRUE ------------------

  GROUNDTRUTH_FILE: "ava_test_gt.csv"
  TEST_LISTS: ["test.csv"]
  TEST_PREDICT_BOX_LISTS: ["ava_test_predicted_boxes.csv"]

  DETECTION_SCORE_THRESH: 0.0
  FRAME_LIST_DIR:    "../ava/frame_lists"
  FRAME_DIR:         "../ava/frames"
  ANNOTATION_DIR:    "../ava/annotations"
  FULL_TEST_ON_VAL: True
  TRAIN_GT_BOX_LISTS: ["ava_train.csv"]
  LABEL_MAP_FILE: "label_map.pbtxt"

DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]

DETECTION:
  ENABLE: True
  ALIGNED: True
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
  SPATIAL_DILATIONS: [[1], [1], [1], [2]]
  SPATIAL_STRIDES: [[1], [2], [2], [1]]
NONLOCAL:
  # LOCATION: [[[]], [[]], [[]], [[]]]
  # NLN config:
  LOCATION: [[[]], [[1, 3]], [[1, 3, 5]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 30, 40]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 50
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0