TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  #CHECKPOINT_FILE_PATH: 
  #CHECKPOINT_TYPE: caffe2
  MIXED_PRECISION: True

TEST:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 4
  CHECKPOINT_FILE_PATH: 

OUTPUT_DIR: /home/lqi/lqi_temp/trainingspace/results/BLIP2

AVA:
  # train 和 test 每次都需要改

  GROUNDTRUTH_FILE: "ava_val_gt.csv"
  TEST_LISTS: ["val.csv"]
  TEST_PREDICT_BOX_LISTS: ["ava_val_predicted_boxes.csv"]

  # GROUNDTRUTH_FILE: "ava_test_gt.csv"
  # TEST_LISTS: ["test.csv"]
  # TEST_PREDICT_BOX_LISTS: ["ava_test_predicted_boxes.csv"]

  DETECTION_SCORE_THRESH: 0.0
  FRAME_LIST_DIR:    "../ava/frame_lists"
  FRAME_DIR:         "../ava/frames"
  ANNOTATION_DIR:    "../ava/annotations"
  FULL_TEST_ON_VAL: True
  TRAIN_GT_BOX_LISTS: ["ava_train.csv"]
  LABEL_MAP_FILE: "label_map.pbtxt"

DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
DETECTION:
  ENABLE: True
  ALIGNED: True
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
  SPATIAL_DILATIONS: [[1], [1], [1], [2]]
  SPATIAL_STRIDES: [[1], [2], [2], [1]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  # NLN config:
  # LOCATION: [[[]], [[1, 3]], [[1, 3, 5]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200

SOLVER:
  OPTIMIZING_METHOD: sgd
  BASE_LR: 0.01                     # 初始学习率
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 5, 10, 20, 30]         # 在 epoch 0、5、10、20、30 五个点调整
  LRS:   [1.0, 0.5, 0.2, 0.05, 0.01] # 分别乘以 BASE_LR 的比例
  MAX_EPOCH: 40
  WARMUP_EPOCHS: 3.0                # 预热 3 轮
  WARMUP_START_LR: 1e-5             # 预热起始 LR


MODEL:
  NUM_CLASSES: 50
  ARCH: blip2
  MODEL_NAME: Blip2VideoModel   
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
  HEAD_ACT: none

  # —— BLIP-2 专属设置 —— 
  BLIP2:
    PRETRAINED: "Salesforce/blip2-flan-t5-xl"
    FREEZE: true
DATA_LOADER:
  NUM_WORKERS: 12
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0