TRAIN:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 48
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: true
  CHECKPOINT_FILE_PATH: /home/lqi/lqi_temp/trainingspace/pretrained_models/MVIT_B_16x4.pyth
  CHECKPOINT_EPOCH_RESET: true
  CHECKPOINT_TYPE: pytorch
  MIXED_PRECISION: true

OUTPUT_DIR: /home/lqi/lqi_temp/trainingspace/results/MVIT_B_16x4

TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 4
  NUM_SPATIAL_CROPS: 1
  CHECKPOINT_FILE_PATH: /home/lqi/lqi_temp/trainingspace/results/MVIT_B_16x4/checkpoints/checkpoint_epoch_00050.pyth

AVA:
  # train 和 test 每次都需要改

  # GROUNDTRUTH_FILE: "ava_val_gt.csv"
  # TEST_LISTS: ["val.csv"]
  # TEST_PREDICT_BOX_LISTS: ["ava_val_predicted_boxes.csv"]

  GROUNDTRUTH_FILE: "ava_test_gt.csv"
  TEST_LISTS: ["test.csv"]
  TEST_PREDICT_BOX_LISTS: ["ava_test_predicted_boxes.csv"]

  DETECTION_SCORE_THRESH: 0.0
  FRAME_LIST_DIR:    "../ava/frame_lists"
  FRAME_DIR:         "../ava/frames"
  ANNOTATION_DIR:    "../ava/annotations"
  FULL_TEST_ON_VAL: True
  TRAIN_GT_BOX_LISTS: ["ava_train.csv"]
  LABEL_MAP_FILE: "label_map.pbtxt"

DETECTION:
  ENABLE: True           # 必开：行为检测分支
  ALIGNED: True

DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: "../ava"           # ← 加上根目录路径
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
MVIT:
  ZERO_DECAY_POS_CLS: False
  SEP_POS_EMBED: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]
  DROPOUT_RATE: 0.0
AUG:
  NUM_SAMPLE: 2
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: False

BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.0001
  CLIP_GRAD_L2NORM: 1.0
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 30, 40, 50]
  LRS: [1, 0.1, 0.01, 0.001, 0.0001]
  MAX_EPOCH: 60
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 1e-6
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 50          # ← 按你的 label_map.pbtxt
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
  HEAD_ACT: none


DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
