TRAIN:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /home/lqi/lqi_temp/trainingspace/pretrained_models/x3d_s.pyth
  CHECKPOINT_EPOCH_RESET: true
  CHECKPOINT_TYPE: pytorch
  MIXED_PRECISION: true

OUTPUT_DIR: /home/lqi/lqi_temp/trainingspace/results/X3D_S

TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 4
  CHECKPOINT_FILE_PATH: /home/lqi/lqi_temp/trainingspace/results/X3D_S/checkpoints/checkpoint_epoch_00035.pyth
  NUM_SPATIAL_CROPS: 3

AVA:
  # train 和 test 每次都需要改

  # GROUNDTRUTH_FILE: "ava_val_gt.csv"
  # TEST_LISTS: ["val.csv"]
  # TEST_PREDICT_BOX_LISTS: ["ava_val_predicted_boxes.csv"]

  GROUNDTRUTH_FILE: "ava_test_gt.csv"
  TEST_LISTS: ["test.csv"]
  TEST_PREDICT_BOX_LISTS: ["ava_test_predicted_boxes.csv"]

  DETECTION_SCORE_THRESH: 0.0
  FRAME_LIST_DIR:    "../ava/frame_lists"
  FRAME_DIR:         "../ava/frames"
  ANNOTATION_DIR:    "../ava/annotations"
  FULL_TEST_ON_VAL: True
  TRAIN_GT_BOX_LISTS: ["ava_train.csv"]
  LABEL_MAP_FILE: "label_map.pbtxt"

X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12

DATA:
  NUM_FRAMES: 13
  SAMPLING_RATE: 6
  TRAIN_JITTER_SCALES: [182, 228]
  TRAIN_CROP_SIZE: 160
  # TEST_CROP_SIZE: 160 # use if TEST.NUM_SPATIAL_CROPS: 1
  TEST_CROP_SIZE: 182 # use if TEST.NUM_SPATIAL_CROPS: 3
  INPUT_CHANNEL_NUM: [3]
  DECODING_BACKEND: torchvision

DETECTION:
  ENABLE: True
  ALIGNED: True
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 30, 40]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 50
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
  HEAD_ACT: none
DATA_LOADER:
  NUM_WORKERS: 12
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
