TRAIN:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 16
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /home/lqi/lqi_temp/trainingspace/pretrained_models/x3d_l.pyth
  CHECKPOINT_EPOCH_RESET: true
  CHECKPOINT_TYPE: pytorch
  MIXED_PRECISION: true

OUTPUT_DIR: /home/lqi/lqi_temp/trainingspace/results/X3D_L

TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 4
  CHECKPOINT_FILE_PATH: /home/lqi/lqi_temp/trainingspace/results/X3D_L/checkpoints/checkpoint_epoch_00030.pyth
  NUM_SPATIAL_CROPS: 3

AVA:
  # train 和 test 每次都需要改

  # GROUNDTRUTH_FILE: "ava_val_gt.csv"
  # TEST_LISTS: ["val.csv"]
  # TEST_PREDICT_BOX_LISTS: ["ava_val_predicted_boxes.csv"]

  GROUNDTRUTH_FILE: "ava_test_gt.csv"
  TEST_LISTS: ["test.csv"]
  TEST_PREDICT_BOX_LISTS: ["ava_test_predicted_boxes.csv"]

  DETECTION_SCORE_THRESH: 0.0
  FRAME_LIST_DIR:    "../ava/frame_lists"
  FRAME_DIR:         "../ava/frames"
  ANNOTATION_DIR:    "../ava/annotations"
  FULL_TEST_ON_VAL: True
  TRAIN_GT_BOX_LISTS: ["ava_train.csv"]
  LABEL_MAP_FILE: "label_map.pbtxt"

X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 5.0
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12

DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [356, 446]
  TRAIN_CROP_SIZE: 312
  # TEST_CROP_SIZE: 312 # use if TEST.NUM_SPATIAL_CROPS: 1
  TEST_CROP_SIZE: 356 # use if TEST.NUM_SPATIAL_CROPS: 3
  INPUT_CHANNEL_NUM: [3]
  DECODING_BACKEND: torchvision
DETECTION:
  ENABLE: True
  ALIGNED: True
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1                          # 初始学习率保持不变
  LR_POLICY: steps_with_relative_lrs   # 分段相对学习率策略
  STEPS: [0, 20, 30, 36]               # 最后一次学习率下降提前到第18个 epoch
  LRS: [1, 0.1, 0.01, 0.001]           # 对应每个 STEP 的相对缩放因子
  MAX_EPOCH: 40                        # 总训练轮数提高到25，使最后阶段有足够训练
  MOMENTUM: 0.9                        # 经典动量值
  WEIGHT_DECAY: 1e-5                   # 提高到1e-5以增加正则化
  WARMUP_EPOCHS: 5.0                   # 预热5个 epoch（占20%训练期）
  WARMUP_START_LR: 0.000125            # 预热起始学习率保持不变
  OPTIMIZING_METHOD: sgd               # 优化器类型不变

MODEL:
  NUM_CLASSES: 50
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
  HEAD_ACT: none
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0

